### ISSUE TITLE
How to use the new MuitipartRequestServerExtension() with a Custom-HttpProcessor ?

### ISSUE THREAD

**Issue by sergiocbueno** [graphql-aspnet/graphql-aspnet#114]
Hi,

After the [GraphQL File Upload Support](https://github.com/graphql-aspnet/graphql-aspnet/issues/104) was released I tried to integrate it into my solution which already contains a custom HTTP processor. However, the features are conflicting, as seen in my Program.cs (DI settings).

![image](https://user-images.githubusercontent.com/46008407/237041631-1b197166-44a5-4579-a14c-f0b52017cf97.png)

When I try to start up my solution I have this error below:

![image](https://user-images.githubusercontent.com/46008407/237041310-819b1ab7-2f7b-4572-9c9a-fa315ebaebb6.png)

I've already tried to change the settings order but then I received an "overwrite" error, where it seems HttpProcessorType of MultipartRequestServerExtension was removed/overwritten by my custom HTTP processor, as you can see below:

![image](https://user-images.githubusercontent.com/46008407/237043069-ffaff5c7-a17c-4a2f-a86f-f7b5086784b6.png)
![image](https://user-images.githubusercontent.com/46008407/237043448-b35fefd0-b383-4cb9-a407-f755a27b6615.png)

Could someone help me by making my custom HTTP Processor and MultipartRequestServerExtension work together?

PS. So far to unblock me I create another schema for managing file upload, it is working but it's still a workaround.

Tks

**Comment by kevin-carroll** [comment]
Hey Sergio,

The file uploads and batch query stuff (the multi-part schema support) is done at the http level, inside the processor. This is so the trappings of file management don't pollute the core engine and all the features remain 100% optional since it does add some overhead for handling http requests.  

It has some checks in there to ensure that if you register the extension to the schema that the work its supposed to do can still function. Its a safeguard to ensure that things don't just break quietly under the hood. This is what you're running in to.

You can can get around it though.

## Option 1 Inherit from the Multipart Processor:
If your `WebGatewayHttpProcessor` is not a complete rewrite of the base processor you probably inherit from `DefaultGraphQLHttpProcessor<TSchema>`?   

If that's the case, you'll want your processor to inherit from `MultipartRequestGraphQLHttpProcessor<TSchema>` ([Source File](https://github.com/graphql-aspnet/graphql-aspnet/blob/master/src/graphql-aspnet/ServerExtensions/MultipartRequests/Engine/MultipartRequestGraphQLHttpProcessor.cs)) instead. There are some differences from the default.  It has some extra methods for splitting the posted form and wrapping the submitted files.  Also a lot of the overloadable methods can be triggered multiple times when processing a batch query.

```csharp
// startup code
services.AddGraphQL(options => {
    options.QueryHandler.httpProcessorType = typeof(WebGratewayHttpProcessor);
    
    options.AddMultipartRequestSupport(mpOptions => {
         // prevent the extension from trying to register its own processor 
         // but still check that the schema's processor inherits from the multipart processor
         mpOptions.RegisterMultipartRequestHttpProcessor = false;
    });
});
```

## Option 2 Use the Multipart Parser with your Own Processor:
Alternatively, if you have done a complete rewrite of the core processor there exists an interface `IMultiPartHttpFormPayloadParser<TSchema>` ([Implementation Source FIle](https://github.com/graphql-aspnet/graphql-aspnet/blob/master/src/graphql-aspnet/ServerExtensions/MultipartRequests/Web/MultiPartHttpFormPayloadParser.cs)) which is injected to the DI container. You can use this to generate a nice [usable object](https://github.com/graphql-aspnet/graphql-aspnet/blob/master/src/graphql-aspnet/ServerExtensions/MultipartRequests/Web/MultiPartRequestGraphQLPayload.cs) that encapsulates everything from the http context. You'll need to manually submit each query (if you do batch queries) to the runtime and aggregate the results (take a peak and the multipart processor for details) but all the logic of parsing the request into objects the engine understands should be black boxed for you.

When using a completely custom processor you'll want to disable the extension's ability to check for processor requirements:
```csharp
// startup code
services.AddGraphQL(options => {
    options.QueryHandler.httpProcessorType = typeof(WebGratewayHttpProcessor);
    
    options.AddMultipartRequestSupport(mpOptions => {
         // Disable all processor checks. The extension will use whatever you provide.
         mpOptions.RegisterMultipartRequestHttpProcessor = false;
         mpOptions.RequireMultipartRequestHttpProcessor= false;
    });
});
```


Definitely open to feedback on how we might improve the extension and make it work better for you. 

Cheers,
Kevin

P.S. A 2.0 feature I'll be adding (and an oversight for v1) is a middleware pipeline for the http side of things. That should solve all this single conflicting processor stuff and add a new level of pluggability to extensions. It wasn't something I anticipated at the start.  Live and learn as they say :)

**Comment by sergiocbueno** [comment]
Thanks @kevin-carroll,

I chose the option 1 approach and after making some modifications in my custom http processor due to the new inheritance of MultipartRequestGraphQLHttpProcessor<TSchema>, it finally works for me.

Well done for the work you have been doing here!
