### ISSUE TITLE
EF Core lazy-loading proxies trigger rule 6.4.3

### ISSUE THREAD

**Issue by Schwefelhexa** [graphql-aspnet/graphql-aspnet#23]
When using `Microsoft.EntityFrameworkCore.Proxies` for lazy-loading the relations, rule 6.4.3 of the GraphQL spec is triggered.

This is because the actual models, e.g. `Person` are wrapped by a proxy class like `Castle.Proxies.PersonProxy` that extend the actual model.

The critical class is `GraphQL.AspNet.ValidationRules.RuleSets.FieldResolution.FieldCompletion.Rule_6_4_3_ServerValueCompletion`, specifically line 65. `context.Schema.KnownTypes.FindGraphType()` returns null, since the proxy is not registered.

I'm not sure what the best solution is, especially because I just started looking into the source code.

**Comment by Schwefelhexa** [comment]
Maybe `SchemaTypeCollection.EnsureGraphType` could check if a proxy class exists in any currently running assembly, and map it to the same graph type.

This feels super hacky tough and not maintainable. Do you have a better idea how to handle this?

**Comment by kevin-carroll** [comment]
Hey @Schwefelhexa  thanks for opening the issue!

Could you provide a quick code example (or point me to an example) that would encapsulate the condition in how you've set things up for your scenario? 

If memory serves there are a few ways to configure or make use of EFCore proxies and I'd like to start with the scenario you are trying right now. 

The devil is in the details when it comes to how `Schema.KnownTypes` is hydrated when the type library is built at runtime and from the description it sounds like a mismatch of the internally developed schema vs. its runtime use/characteristics.  I'd love to explore the problem a bit deeper. 

I agree that a mapping feels a bit hacky, I'm sure there is a better solution.

**Comment by Schwefelhexa** [comment]
Hi @kevin-carroll thanks for the quick response!

Check out an example I made [here](https://github.com/Schwefelhexa/graphql-aspnet-repro-23).

I couldn't find a way to configure proxies, because `.UseLazyLoadingProxies()` doesn't take any parameters. I will look into it though, maybe we find something useful.

**Comment by Schwefelhexa** [comment]
I might have found a solution.

When a function is declared to return, say, an object of type `Donut`, instead of forcing an exact type match, we could allow any type extending `Donut` to be valid.
Since the schema only declares the fields of `Donut`, anything added by the extending class can't be queried, so there are no security issues with that.

**Comment by kevin-carroll** [comment]
That's a fantastic point! Especially from the security and query validation stand point.

A few things pop into my head from that though.  Lets say we have the object `DonutProxy`, that logically inherits from `Donut` and so `FindGraphType` _could_ map it correctly to the `Donut` graph type, fixing the error. But since `DonutProxy` is not known to the schema we need to do some type walking (at run time) to inspect the inheritance tree to find a match.  Doable, but slow.  We could cache the results of the "DonutProxy to Donut" relationship and thus only incur a hit the first time.  That could be acceptable.

But what if the inheritance chain is deeper.  What if `Donut` inherits from `Pastry` and `Pastry` is also a known graph type.  Then when we are trying to the resolve the .NET class `DonutProxy` (which extends `Donut`), how do we know which graph type to return in the moment? `Donut` or `Pastry`?  If we cached a relationship we'd risk a logic error in that `DonutProxy` always is a `Donut` graph type but logically it could, in another query, want or need to be a `Pastry` from the perspective of the query provided. 

Continuing on that line of thought though.  Perhaps we could allow the developer to extend `GraphValdiation.EliminateWrappersFromCoreType` (line 64 on the failing rule) and let the individual developer declare what he/she wants to remove from a wrapped or extended type before letting the schema map it to a graph type. 

Right now `EliminateWrappersFromCoreType` only handles the basics (`Task<T>`, `Nullable<T>`, `IEnumerable<T>` etc.) but at first glance there isn't a reason to deny the user an ability to supply a `Func<Type, Type>` at start up to accept a type, perform some logic against it (e.g. see `DonutProxy` and return `Donut`) then let the type system take over. 

Does EFCore Proxies keep a set of relationships between the base types and the proxies it generates? If so that seems like a great place to call into EFCore Proxies and (with great accuracy) extract the actual class from its proxied entity.

That would eliminate any presumptions by the graph engine from trying to determine where (or what) in a class's inheritance tree to eliminate vs. use when mapping a type.

Startup code might be something like this. (Im guessing here as to the abilities of EFCore Proxies and its API.):

```
services.AddGraphQL(options =>
      {
          options.Extensions.TypeFilters.Add(((Type proxyType) => {
                return EfCoreProxies.FindTypeFromProxy(proxyType);
         })
      });
```

**Comment by Schwefelhexa** [comment]
I found a solution!
`dbContext.Entry(proxiedDonut).CurrentValues.EntityType.ClrType` returns the `Donut` type.

Now we just need to figure out how to feed the `dbContext` into the mapping function.

**Comment by Schwefelhexa** [comment]
This sounds great, can't wait to see it!

**Comment by kevin-carroll** [comment]
`v0.6.0-beta` should resolve this conflict.
