### ISSUE TITLE
Schema with mandatory and optional attributes

### ISSUE THREAD

**Issue by nicolaspfernandes** [graphql-aspnet/graphql-aspnet#47]
I couldn't find anywhere in the docs:
If I create a class that will represent a GraphQL Input object, ALL my attributes are optional.
Is there a way to make them mandatory with Annotations?

**Comment by kevin-carroll** [comment]
Hey Nicolas,

By default any reference types will always be optional (since the can be null). The easiest way to force their inclusion would be to set a custom `TypeExpression` through the `[GraphField]` attribute.

This will force the user to declare `Prop1` as part of the input object or it will be rejected.

```csharp
    public class SampleInputObject
    {
        [GraphField(TypeExpression = TypeExpressions.IsNotNull)]]
        public string Prop1 { get; set; }
    }
```

![image](https://user-images.githubusercontent.com/23524037/142741960-97af5ade-16e0-4dfe-aac1-c93924a683bf.png)


Looks like the additional option for [GraphField] are not in the documentation. I'll take an action item to get that updated. Thanks for bringing this up!

Cheers,
Kevin

**Comment by nicolaspfernandes** [comment]
Thanks, Kevin! Please bring this up to the docs, it could help some other lads are looking for the info! Cheers
